### PR TITLE
Fix local Post API for csb/stackblitz

### LINKED ISSUE #294: The Post API form for CSB/Stackblitz uses only the shared assets from the last fetched shared.json
This does not have an impact on production/staging

### PR DESCRIPTION
**Pull request by dobromirts**
Closes #294

### CODE REVIEW

File: src/app/services/code-view/angular-code-service.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ export class AngularCodeService extends CodeService {
     private sampleFilesContentByUrl: { [url: string]: any } = {};
     private demosTimeStamp: number;
     private sharedFileContent: { [url: string]: any } = {};
+    private localDemosUrls : number = 0;
```
Comment (HristoP96) [inline src/app/services/code-view/angular-code-service.ts:20]: The code service classes are singletons soo this is not optimal approach

**Review by HristoP96 — COMMENTED** [review]
Try fixing this issue by adding the diffrent demosBaseUrls values as keys to the sampleFilesContent adn the respective data as their values, without adding a counter.

File: src/app/services/code-view/angular-code-service.ts [hunk 2]
```diff
@@ -226,11 +235,24 @@ export class AngularCodeService extends CodeService {
...
             }
-            let formData = {
-                dependencies: sampleContent.sampleDependencies,
-                files: codeService.sharedFileContent.files.concat(sampleContent.sampleFiles),
-                devDependencies: codeService.sharedFileContent.devDependencies
+
+            let formData = {};
+
+            if(util.isLocalhost && codeService.localDemosUrls > 1){
+                const key :any = $codeView[0].dataset["demosBaseUrl"];
```
Comment (HristoP96) [inline src/app/services/code-view/angular-code-service.ts:242]: You can get the baseUrl from the code view with the demosBaseUrlAttrName attribute of the code view

**Review by HristoP96 — CHANGES_REQUESTED** [review]

File: src/app/services/code-view/angular-code-service.ts [hunk 3]
```diff
@@ -191,7 +193,13 @@ export class AngularCodeService extends CodeService {
         return function (this: JQuery.UrlAjaxSettings, data: any) {
             const files = data.files;
             codeService.replaceRelativeAssetsUrls(files, demosBaseUrl);
-            codeService.sharedFileContent = data;
+
+            if (util.isLocalhost && codeService.demosUrlsSize > 1){
```
Comment (HristoP96) [inline src/app/services/code-view/angular-code-service.ts:197]: util.isLocalhost is redundant since this function will be used only under localhost

File: src/app/services/code-view/angular-code-service.ts [hunk 4]
```diff
@@ -226,11 +234,24 @@ export class AngularCodeService extends CodeService {
...
                 codeService.sharedFileContent.files.push(codeService.sharedFileContent.tsConfig)
             }
-            let formData = {
-                dependencies: sampleContent.sampleDependencies,
-                files: codeService.sharedFileContent.files.concat(sampleContent.sampleFiles),
-                devDependencies: codeService.sharedFileContent.devDependencies
+
+            let formData = {};
+
+            if(util.isLocalhost && codeService.demosUrlsSize > 1){
```
Comment (HristoP96) [inline src/app/services/code-view/angular-code-service.ts:240]: the same as the comment above

**Review by HristoP96 — CHANGES_REQUESTED** [review]
Try achieving this without the need of a counter or demosUrlsSize, just add each demosBaseUrl as a key directly, without any checks to the sharedFileContent even if there is only one demosBaseUrl

**Review by HristoP96 — APPROVED** [review]
